"""empty message

Revision ID: 041a7377b29c
Revises: fbc1f2eccdcd
Create Date: 2025-11-23 02:30:01.612117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '041a7377b29c'
down_revision = 'fbc1f2eccdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('golongan', sa.String(length=50), nullable=True))
        batch_op.alter_column('harga',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obat', schema=None) as batch_op:
        batch_op.alter_column('harga',
               existing_type=sa.String(length=100),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('golongan')

    # ### end Alembic commands ###
