"""add gambar to obat

Revision ID: 0edcb9491f4d
Revises: d7373daba94e
Create Date: 2025-11-24 04:31:25.434322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edcb9491f4d'
down_revision = 'd7373daba94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gambar', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obat', schema=None) as batch_op:
        batch_op.drop_column('gambar')

    # ### end Alembic commands ###
