"""update rule model

Revision ID: 23a634e16daa
Revises: 0edcb9491f4d
Create Date: 2025-12-08 23:57:39.719566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23a634e16daa'
down_revision = '0edcb9491f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_detail')
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori_kode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('nilai_kepercayaan', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'kategori_obat', ['kategori_kode'], ['kode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nilai_kepercayaan')
        batch_op.drop_column('kategori_kode')

    op.create_table('rule_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_kode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('nilai_kepercayaan', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_kode'], ['kategori_obat.kode'], name=op.f('rule_detail_ibfk_1')),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], name=op.f('rule_detail_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
