"""empty message

Revision ID: d7373daba94e
Revises: 041a7377b29c
Create Date: 2025-11-23 03:03:27.150771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7373daba94e'
down_revision = '041a7377b29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('kategori_kode', sa.String(length=10), nullable=True),
    sa.Column('nilai_kepercayaan', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_kode'], ['kategori_obat.kode'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rule_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('nilai_kepercayaan')
        batch_op.drop_column('obat_kode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obat_kode', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('nilai_kepercayaan', mysql.FLOAT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('rule_ibfk_2'), 'obat', ['obat_kode'], ['kode'])

    op.drop_table('rule_detail')
    # ### end Alembic commands ###
