"""update rule model lagi

Revision ID: ef71757e40d7
Revises: 23a634e16daa
Create Date: 2025-12-09 23:00:16.366550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef71757e40d7'
down_revision = '23a634e16daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori_list', sa.String(length=255), nullable=False))
        batch_op.alter_column('gejala_kode',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('nilai_kepercayaan',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('rule_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('kategori_kode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori_kode', mysql.VARCHAR(length=10), nullable=True))
        batch_op.create_foreign_key(batch_op.f('rule_ibfk_2'), 'kategori_obat', ['kategori_kode'], ['kode'])
        batch_op.alter_column('nilai_kepercayaan',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('gejala_kode',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('kategori_list')

    # ### end Alembic commands ###
