"""initial

Revision ID: fbc1f2eccdcd
Revises: 
Create Date: 2025-11-23 01:41:45.103279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc1f2eccdcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gejala',
    sa.Column('kode', sa.String(length=10), nullable=False),
    sa.Column('nama_gejala', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('kode')
    )
    op.create_table('kategori_obat',
    sa.Column('kode', sa.String(length=10), nullable=False),
    sa.Column('nama_kategori', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('kode')
    )
    op.create_table('obat',
    sa.Column('kode', sa.String(length=10), nullable=False),
    sa.Column('nama_obat', sa.String(length=200), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('indikasi', sa.Text(), nullable=True),
    sa.Column('komposisi', sa.Text(), nullable=True),
    sa.Column('dosis', sa.Text(), nullable=True),
    sa.Column('kontraindikasi', sa.Text(), nullable=True),
    sa.Column('efek_samping', sa.Text(), nullable=True),
    sa.Column('harga', sa.Float(), nullable=True),
    sa.Column('manufaktur', sa.String(length=200), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('kategori_kode', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['kategori_kode'], ['kategori_obat.kode'], ),
    sa.PrimaryKeyConstraint('kode')
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gejala_kode', sa.String(length=10), nullable=True),
    sa.Column('obat_kode', sa.String(length=10), nullable=True),
    sa.Column('nilai_kepercayaan', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gejala_kode'], ['gejala.kode'], ),
    sa.ForeignKeyConstraint(['obat_kode'], ['obat.kode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule')
    op.drop_table('obat')
    op.drop_table('kategori_obat')
    op.drop_table('gejala')
    op.drop_table('admin')
    # ### end Alembic commands ###
